{
  "PRed": [
    {
      "PR": {
        "__lazy_json__": "pr_json/581843056.json"
      },
      "data": {
        "bot_rerun": false,
        "migrator_name": "Version",
        "migrator_version": 0,
        "version": "2020-12-09"
      },
      "keys": [
        "bot_rerun",
        "migrator_name",
        "migrator_version",
        "version"
      ]
    }
  ],
  "bad": false,
  "pinning_version": "2021.02.26.15.36.03",
  "pre_pr_migrator_attempts": {
    "version": 1
  },
  "pre_pr_migrator_status": {
    "version": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/607786625\">bot CI job</a>): master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1082, in main\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 225, in run\n    eval_cmd(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 224, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/subprocess.py\", line 448, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
  },
  "smithy_version": "3.9.0"
}