{
  "bad": false,
  "new_version": "3.46.0.8",
  "new_version_attempt_ts": {
    "3.40.0.1": 1758369191.0,
    "3.46.0.1": 1758340391.0,
    "3.46.0.7": 1759931220,
    "3.46.0.8": 1761620538
  },
  "new_version_attempts": {
    "3.30.0.5": 1,
    "3.30.0.6": 1,
    "3.30.0.7": 1,
    "3.30.1.1": 1,
    "3.30.1.2": 1,
    "3.30.1.3": 1,
    "3.32.0.2": 1,
    "3.32.0.3": 1,
    "3.32.0.4": 1,
    "3.32.0.5": 1,
    "3.32.1.1": 1,
    "3.32.1.2": 1,
    "3.32.1.3": 1,
    "3.32.1.4": 1,
    "3.32.1.5": 1,
    "3.32.1.6": 1,
    "3.32.1.7": 1,
    "3.34.0.1": 1,
    "3.35.0.2": 1,
    "3.36.0.1": 1,
    "3.36.0.2": 1,
    "3.36.0.3": 1,
    "3.36.0.4": 1,
    "3.36.1.1": 1,
    "3.36.1.2": 1,
    "3.36.1.3": 1,
    "3.36.1.4": 1,
    "3.36.1.5": 1,
    "3.38.0.1": 1,
    "3.38.0.2": 1,
    "3.38.0.3": 1,
    "3.38.0.4": 2,
    "3.40.0.1": 6,
    "3.40.0.2": 1,
    "3.40.0.3": 1,
    "3.40.0.4": 1,
    "3.42.0.1": 1,
    "3.42.0.2": 1,
    "3.42.0.3": 1,
    "3.42.0.4": 1,
    "3.44.0.1": 1,
    "3.44.0.2": 1,
    "3.44.0.3": 1,
    "3.46.0.1": 14,
    "3.46.0.2": 1,
    "3.46.0.7": 614,
    "3.46.0.8": 50
  },
  "new_version_errors": {
    "3.40.0.1": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '3.40.0.1' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n",
    "3.46.0.1": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '3.46.0.1' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n",
    "3.46.0.7": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/18346568125\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 233, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 270, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 311, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '3.46.0.7' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n\n",
    "3.46.0.8": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/18862521016\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 233, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 270, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 311, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '3.46.0.8' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n\n"
  }
}