{
  "bad": false,
  "new_version": "11.1",
  "new_version_attempt_ts": {
    "10.1": 1758386466.0,
    "10.2": 1758386466.0,
    "10.3": 1758354786.0,
    "10.3.1": 1758390786.0,
    "11.1": 1758381426.0,
    "8.3": 1758359106.0,
    "8.4": 1758385746.0,
    "8.4.1": 1758386466.0,
    "8.5": 1758389346.0,
    "8.5.1": 1758390786.0,
    "9.0": 1758385746.0,
    "9.0.1": 1758373506.0,
    "9.1": 1758385746.0,
    "9.1.1": 1758385746.0,
    "9.2": 1758383586.0
  },
  "new_version_attempts": {
    "10.1": 1.2,
    "10.2": 1.2,
    "10.3": 10,
    "10.3.1": 0,
    "11.1": 2.6000000000000005,
    "6.2.1": 2,
    "6.2.2": 2,
    "7.0": 1,
    "7.0.1": 1,
    "7.1": 1,
    "7.2": 1,
    "7.3": 2,
    "8.0": 1,
    "8.1": 1,
    "8.2": 1,
    "8.3": 8.799999999999997,
    "8.4": 1.4,
    "8.4.1": 1.2,
    "8.5": 0.3999999999999999,
    "8.5.1": 0,
    "9.0": 1.4,
    "9.0.1": 4.8000000000000025,
    "9.1": 1.4,
    "9.1.1": 1.4,
    "9.2": 2
  },
  "new_version_errors": {
    "10.1": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7150582080'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                osx_64_python3.10.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.11.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.12.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.8.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.9.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.10.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.11.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.12.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.9.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.1.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
    "10.2": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8307407182'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                osx_64_python3.10.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.11.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.12.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.8.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_python3.9.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.10.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.11.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.12.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_arm64_python3.9.____cpython: Could not solve for environment specs\nThe following package could not be installed\n└─ pyobjc-core 10.2.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
    "10.3": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9450823019\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 572, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run(\n                            ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 216, in run\n    migration_run_data = run_migration(\n                         ^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 63, in run_migration\n    return run_migration_containerized(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 157, in run_migration_containerized\n    data = run_container_task(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 249, in run_container_task\n    raise RuntimeError(\nRuntimeError: Error running migrate-feedstock in container - error VersionMigrationError(\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\\n\\nPlease check the URLs in your recipe with version '10.3' to make sure they exist!\\n\\nWe also found the following errors:\\n\\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\\n\") raised:\ncmd: ['docker',\n 'run',\n '-e',\n 'CF_TICK_IN_CONTAINER=true',\n '--security-opt=no-new-privileges',\n '--read-only',\n '--cap-drop=all',\n '--mount',\n 'type=tmpfs,destination=/tmp,tmpfs-mode=1777,tmpfs-size=6000000000',\n '-m',\n '6000m',\n '--cpus',\n '1',\n '--ulimit',\n 'nofile=1024:1024',\n '--ulimit',\n 'nproc=2048:2048',\n '--rm',\n '-i',\n '--mount',\n 'type=bind,source=/tmp/tmpnbkcuk9a,destination=/cf_tick_dir',\n 'ghcr.io/regro/conda-forge-tick:master',\n '/opt/conda/envs/cf-scripts/bin/python',\n '-u',\n '/opt/autotick-bot/docker/run_bot_task.py',\n 'migrate-feedstock',\n '--feedstock-name',\n 'pyobjc-framework-cocoa',\n '--default-branch',\n 'main',\n '--existing-feedstock-node-attrs',\n '-',\n '--kwargs',\n '{\\n \"hash_type\": \"sha256\"\\n}',\n '--log-level',\n 'info']\nstdout: {'data': None,\n 'default_branch': 'main',\n 'error': 'VersionMigrationError(\"The recipe did not change in the version '\n          'migration, a URL did not hash, or there is jinja2 syntax the bot '\n          'cannot handle!\\\\n\\\\nPlease check the URLs in your recipe with '\n          \"version '10.3' to make sure they exist!\\\\n\\\\nWe also found the \"\n          'following errors:\\\\n\\\\n - could not hash URL template '\n          \"'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name \"\n          '}}-{{ version }}.tar.gz\\'\\\\n\")',\n 'feedstock_name': 'pyobjc-framework-cocoa',\n 'input_kwargs': '{\\n \"hash_type\": \"sha256\"\\n}',\n 'traceback': 'Traceback (most recent call last):\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 120, in '\n              '_run_bot_task\\n'\n              '    data = func(attrs=attrs, **kwargs)\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 308, in '\n              '_migrate_feedstock\\n'\n              '    data = run_migration_local(\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line '\n              '241, in run_migration_local\\n'\n              '    data[\"migrate_return_value\"] = migrator.migrate(\\n'\n              '                                   ^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line '\n              '215, in migrate\\n'\n              '    raise VersionMigrationError(\\n'\n              'conda_forge_tick.migrators.version.VersionMigrationError: The '\n              'recipe did not change in the version migration, a URL did not '\n              'hash, or there is jinja2 syntax the bot cannot handle!\\n'\n              '\\n'\n              \"Please check the URLs in your recipe with version '10.3' to \"\n              'make sure they exist!\\n'\n              '\\n'\n              'We also found the following errors:\\n'\n              '\\n'\n              ' - could not hash URL template '\n              \"'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ \"\n              \"name }}-{{ version }}.tar.gz'\\n\"\n              '\\n'}\n",
    "10.3.1": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9547837335\">bot CI job</a>): main:\nError running migrate-feedstock in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '10.3.1' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n\"",
    "11.1": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/15712831241'>bot CI job</a>) @ main\n        <details>\n        <div align=\"left\">\n        <pre>\n        osx_64_python3.10.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_64_python3.11.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_64_python3.12.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_64_python3.13.____cp313: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_64_python3.9.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_arm64_python3.10.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_arm64_python3.11.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_arm64_python3.12.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_arm64_python3.13.____cp313: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n</pre><pre>osx_arm64_python3.9.____cpython: Cannot solve the request because of: No candidates were found for pyobjc-core 11.1.*.\n\n        </pre>\n        </div>\n        </details>",
    "8.3": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1945933124\">bot CI job</a>): master: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.3.*\\n', 'osx_64_python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.3.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.3.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.3.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.3.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.3.*\\n']",
    "8.4": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1949427366\">bot CI job</a>): master: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.*\\n', 'osx_64_python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.*\\n']",
    "8.4.1": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1986300229\">bot CI job</a>): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.1.*\\n', 'osx_64_python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.1.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.1.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.1.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.1.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.4.1.*\\n']",
    "8.5": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2190441278\">bot CI job</a>): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.*\\n', 'osx_64_python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.*\\n']",
    "8.5.1": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3079510755\">bot CI job</a>): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.1.*\\n', 'osx_64_python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.1.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.1.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.1.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.1.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 8.5.1.*\\n']",
    "9.0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3401979029\">bot CI job</a>): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.*\\n', 'osx_64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.*\\n', 'osx_arm64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.*\\n']",
    "9.0.1": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4708043586\">bot CI job</a>): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.1.*\\n', 'osx_64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.1.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.1.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.1.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.1.*\\n', 'osx_arm64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.1.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.0.1.*\\n']",
    "9.1": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4713262363\">bot CI job</a>): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.*\\n', 'osx_64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.*\\n', 'osx_arm64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.*\\n']",
    "9.1.1": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4732549109\">bot CI job</a>): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.1.*\\n', 'osx_64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.1.*\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.1.*\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.1.*\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.1.*\\n', 'osx_arm64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.1.*\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pyobjc-core 9.1.1.*\\n']",
    "9.2": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '9.2' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n"
  }
}