{
  "bad": false,
  "new_version": "9.2.175",
  "new_version_attempt_ts": {
    "9.2.163": 1758282800.0,
    "9.2.164": 1758354800.0
  },
  "new_version_attempts": {
    "9.2.100": 1,
    "9.2.101": 1,
    "9.2.102": 1,
    "9.2.163": 30,
    "9.2.164": 10,
    "9.2.67": 1,
    "9.2.68": 1,
    "9.2.69": 1,
    "9.2.70": 2,
    "9.2.71": 1,
    "9.2.72": 1,
    "9.2.73": 1,
    "9.2.74": 1,
    "9.2.75": 1,
    "9.2.76": 1,
    "9.2.77": 1,
    "9.2.78": 1,
    "9.2.79": 1,
    "9.2.80": 1,
    "9.2.81": 1,
    "9.2.82": 1,
    "9.2.83": 1,
    "9.2.84": 1,
    "9.2.85": 1,
    "9.2.86": 1,
    "9.2.87": 1,
    "9.2.88": 1,
    "9.2.89": 1,
    "9.2.90": 1,
    "9.2.91": 1,
    "9.2.92": 1,
    "9.2.93": 1,
    "9.2.94": 1,
    "9.2.95": 1,
    "9.2.96": 1,
    "9.2.97": 1,
    "9.2.98": 1,
    "9.2.99": 1
  },
  "new_version_errors": {
    "9.2.163": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/16144590875\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 231, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 324, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '9.2.163' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/archinfo-{{ version }}.tar.gz'\n\n",
    "9.2.164": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/16188359666\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 231, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 324, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '9.2.164' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/archinfo-{{ version }}.tar.gz'\n\n"
  }
}