{
  "bad": false,
  "new_version": "1.8.0",
  "new_version_attempts": {
    "1.1.0": 36,
    "1.1.1": 149,
    "1.1.2": 793,
    "1.2.1": 748,
    "1.3.1": 100,
    "1.3.2": 542,
    "1.4.0": 9,
    "1.5.0": 4,
    "1.6.0": 53,
    "1.7.0": 12,
    "1.7.0-1": 4,
    "1.7.1": 810,
    "1.8.0": 75
  },
  "new_version_errors": {
    "1.1.0": "We found a problem parsing the recipe: \n\nwhile constructing a mapping\n  in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10)\nfound duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")\n  in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12)\n\nTo suppress this check see:\n    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n\nDuplicate keys will become an error in future releases, and are errors\nby default when using the new API.\n",
    "1.1.1": "We found a problem parsing the recipe: \n\nwhile constructing a mapping\n  in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10)\nfound duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")\n  in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12)\n\nTo suppress this check see:\n    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n\nDuplicate keys will become an error in future releases, and are errors\nby default when using the new API.\n",
    "1.1.2": "We found a problem parsing the recipe: \n\nwhile constructing a mapping\n  in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10)\nfound duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")\n  in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12)\n\nTo suppress this check see:\n    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n\nDuplicate keys will become an error in future releases, and are errors\nby default when using the new API.\n",
    "1.2.1": "We found a problem parsing the recipe for version '1.2.1': \n\nDuplicateKeyError('while constructing a mapping', <ruamel.yaml.error.StringMark object at 0x7f6ea0306e40>, 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")', <ruamel.yaml.error.StringMark object at 0x7f6ea0306430>, '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 472, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/main.py\", line 343, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 1563, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 1469, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 146, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 188, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 1563, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 295, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "1.3.1": "We found a problem parsing the recipe for version '1.3.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 472, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 421, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 111, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1533, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1447, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 186, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1533, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1448, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 284, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "1.3.2": "We found a problem parsing the recipe for version '1.3.2': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 509, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 494, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "1.4.0": "We found a problem parsing the recipe for version '1.4.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/version.py\", line 521, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "1.5.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.5.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '1.5.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1459, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1348, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 185, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1459, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1349, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 275, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "1.6.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.6.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '1.6.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 514, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/main.py\", line 451, in load\n    return constructor.get_single_data()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 114, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1359, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 145, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 186, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1360, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 276, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "1.7.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.7.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '1.7.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 514, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/main.py\", line 451, in load\n    return constructor.get_single_data()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 114, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1359, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 145, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 186, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1360, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 276, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "1.7.0-1": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/11540468583\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name rb-aws-codedeploy-agent --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n'The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.7.0-1' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '1.7.0-1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 540, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/recipe_parser/_parser.py\", line 525, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/main.py\", line 451, in load\n    return constructor.get_single_data()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 116, in get_single_data\n    return self.construct_document(node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 125, in construct_document\n    for _dummy in generator:\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1476, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1365, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 147, in construct_object\n    data = self.construct_non_recursive_object(node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 188, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1476, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1366, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 278, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n'",
    "1.7.1": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/16822020630\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 231, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 324, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.7.1' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '1.7.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\n                    To suppress this check see:\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\n                    by default when using the new API.\n                    ')\n\ntraceback:\n  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 833, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/recipe_parser/_parser.py\", line 617, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 114, in get_single_data\n    return self.construct_document(node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1359, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 145, in construct_object\n    data = self.construct_non_recursive_object(node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 186, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1360, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 276, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n\n",
    "1.8.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/17201391661\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 231, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 324, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.8.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '1.8.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 10, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 10), 'found duplicate key \"url\" with value \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-1.<{ version }}.tar.gz\" (original value: \"https://github.com/aws/aws-codedeploy-agent/archive/v1.0-<{ version }}.tar.gz\")',   in \"<unicode string>\", line 12, column 3:\n      url: https://github.com/aws/aws- ... \n      ^ (line: 12), '\n                    To suppress this check see:\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\n                    by default when using the new API.\n                    ')\n\ntraceback:\n  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 833, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/recipe_parser/_parser.py\", line 617, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 114, in get_single_data\n    return self.construct_document(node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1359, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 145, in construct_object\n    data = self.construct_non_recursive_object(node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 186, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1360, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 276, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n\n"
  }
}