{
  "PRed": [
    {
      "data": {
        "bot_rerun": false,
        "migrator_name": "Version",
        "migrator_version": 0,
        "version": "1.0.0a2"
      }
    },
    {
      "PR": {
        "number": 2,
        "state": "closed"
      },
      "data": {
        "bot_rerun": false,
        "migrator_name": "CompilerRebuild",
        "migrator_version": 1,
        "name": "Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
      }
    },
    {
      "PR": {
        "number": 3,
        "state": "closed"
      },
      "data": {
        "bot_rerun": false,
        "migrator_name": "Version",
        "migrator_version": 0,
        "version": "2.1.1"
      }
    },
    {
      "PR": {
        "number": 4,
        "state": "closed"
      },
      "data": {
        "bot_rerun": 1669989816.4810765,
        "migrator_name": "MigrationYaml",
        "migrator_object_version": 1,
        "migrator_version": 0,
        "name": "python38"
      }
    },
    {
      "PR": {
        "__lazy_json__": "pr_json/2290799181.json"
      },
      "data": {
        "bot_rerun": false,
        "migrator_name": "NoarchPythonMinMigrator",
        "migrator_version": 1,
        "name": "noarch_python_min"
      }
    }
  ],
  "bad": false,
  "pinning_version": "2025.01.21.10.12.57",
  "pre_pr_migrator_attempt_ts": {
    "pypy": 1758387192.0,
    "pypy37": 1758387192.0,
    "pypy38": 1758246792.0,
    "python310": 1752951192.0,
    "python311": 1758199992.0,
    "python39": 1758387192.0
  },
  "pre_pr_migrator_attempts": {
    "pypy": 1,
    "pypy37": 1,
    "pypy38": 40,
    "python310": 1511,
    "python311": 53,
    "python39": 1
  },
  "pre_pr_migrator_status": {
    "pypy": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/943740893\">bot CI job</a>): master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1132, in main\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 188, in run\n    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/core.py\", line 257, in run_pre_piggyback_migrations\n    if not mini_migrator.filter(attrs):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/use_pip.py\", line 22, in filter\n    return not bool(set(self.bad_install) & set(scripts))\nTypeError: unhashable type: 'dict'\n",
    "pypy37": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1419407741\">bot CI job</a>): master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1128, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 197, in run\n    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/core.py\", line 259, in run_pre_piggyback_migrations\n    if not mini_migrator.filter(attrs):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/use_pip.py\", line 22, in filter\n    return not bool(set(self.bad_install) & set(scripts))\nTypeError: unhashable type: 'dict'\n",
    "pypy38": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3599732028\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1166, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 232, in run\n    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/core.py\", line 263, in run_pre_piggyback_migrations\n    if not mini_migrator.filter(attrs):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/use_pip.py\", line 22, in filter\n    return not bool(set(self.bad_install) & set(scripts))\nTypeError: unhashable type: 'dict'\n",
    "python310": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2915461479\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1150, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 231, in run\n    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/core.py\", line 263, in run_pre_piggyback_migrations\n    if not mini_migrator.filter(attrs):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/use_pip.py\", line 22, in filter\n    return not bool(set(self.bad_install) & set(scripts))\nTypeError: unhashable type: 'dict'\n",
    "python311": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3596346193\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1166, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 232, in run\n    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/core.py\", line 263, in run_pre_piggyback_migrations\n    if not mini_migrator.filter(attrs):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/use_pip.py\", line 22, in filter\n    return not bool(set(self.bad_install) & set(scripts))\nTypeError: unhashable type: 'dict'\n",
    "python39": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/705298520\">bot CI job</a>): master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1135, in main\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 188, in run\n    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/core.py\", line 257, in run_pre_piggyback_migrations\n    if not mini_migrator.filter(attrs):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/use_pip.py\", line 22, in filter\n    return not bool(set(self.bad_install) & set(scripts))\nTypeError: unhashable type: 'dict'\n"
  },
  "smithy_version": "3.45.3"
}